name: tmp-pr-action-test
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  test:
    if: github.event.pull_request.head.ref == 'mobile-migration-v1'
    runs-on: ubuntu-latest
    steps:
      - run: echo PR_ACTION_TEST_OK
